<?php


namespace SM_Elementor\Module\Archive;

use Elementor\Controls_Stack;
use ElementorPro\Plugin;
use Elementor\Controls_Manager;

class Module extends \SM_Elementor\Common\Plugin_Module
{
    /* @return Module */
    static function i($info=[], $context=null) { return parent::i($info, $context); }

    static function info()
    {
        return array(
            'title'        => 'Archive',
            'path'         => __DIR__,
            'classmap'     => [
                'widget' => [
                    'SM_Elementor\Module\Archive\Widget\Calendar'  => array('label' => 'Calendar', 'init'=>true),
                ],
            ],
        );
    }


    function init_events()
    {
        parent::init_events(); // TODO: Change the autogenerated stub

        add_action('wp_ajax_sm_elementor_module_archive_calendar_get_month_grid', [$this, '_action_ajax_calendar_get_month_grid']);
        add_action('wp_ajax_nopriv_sm_elementor_module_archive_calendar_get_month_grid', [$this, '_action_ajax_calendar_get_month_grid']);

        //sm_elementor_module_archive_widget_calendar_get_grid
    }

    function _action_ajax_calendar_get_month_grid()
    {

        $view = new \SM_Elementor\Module\Archive\Calendar\View();

        $view->init_ajax($_REQUEST['settings_protected'], $_REQUEST['query_protected']);

        wp_send_json_success(['content' => $view->get_month_grid($_REQUEST['year'], $_REQUEST['month'])]);
    }


}



