#import "./fragments/Term/Term.gql"
#import "./fragments/Post/Post.gql"
#import "./fragments/Connection/PageInfo.gql"

query (
  $filter: JSON,
  $nav: QueryInputNav,

  $image: Boolean = true,
  $imageSize: String = "d2.4",
  $imageSizes: [String] = [],
  $imageHook: Boolean = true,

  $terms: Boolean = true,
  $termsTaxonomy: [String] = ["category"],

  $hub: Boolean = false,

  $authors: Boolean = false,
  $gallery: Boolean = false,
  $galleryImageSize: String = "d1.25",
  $galleryImageSizes: [String] = ["m1.9", "d1.25", "d1.9", "d2.4"],

  $content: Boolean = false,

  $view: String = "public",
  $queryId: String
) {
  res: getPostsElastic(
    filter: $filter,
    nav: $nav,
    view: $view,
    queryId: $queryId
  ) {
    nodes {
      ...Post

    }
    pageInfo {
      ...PageInfo
    }
  }
}
